### ISSUE TITLE
When I use the module federation exposes parameter packaged complains

### ISSUE THREAD

**Issue by zhoushaw** [jherr/wp5-starter-react#4]
When I use the module federation exposes parameter packaged complains

node-env: v12.18.1
![image](https://user-images.githubusercontent.com/27547179/93742218-51d09a80-fc20-11ea-8a68-1c6841bfeb6d.png)
![image](https://user-images.githubusercontent.com/27547179/93742246-5c8b2f80-fc20-11ea-96b9-19e6ce88040d.png)
![image](https://user-images.githubusercontent.com/27547179/93742261-62811080-fc20-11ea-80e0-6a64b02b3738.png)

**Comment by zhoushaw** [comment]
this problem has be resolve, ModuleFederationPlugin can't use `-` as name parameter part

**Comment by jherr** [comment]
Yeah, you can't use special characters in the name.
