### ISSUE TITLE
This repo  doesnt work with nav header code

### ISSUE THREAD

**Issue by hamzaame** [jherr/wp5-starter-react#5]
Hi,

I am using this repo as boilerplate for react app. Since this doesnt have any component, I tried to create a "Header.jsx" from "nav" package in https://github.com/jherr/wp5-intro-video-code/tree/master/packages/nav .

 

When I try to start the server i get this below errors

 

```
ERROR in ./node_modules/@babel/runtime/helpers/es

Module not found: Error: Can't resolve './setProtelpers\esm'

Did you mean 'setPrototypeOf.js'?

BREAKING CHANGE: The request './setPrototypeOf' f

(probably because the origin is a '*.mjs' file or

The extension in the request is mandatory for it

Add the extension to the request.

@ ./node_modules/@material-ui/core/esm/RootRef/R

@ ./node_modules/@material-ui/core/esm/RootRef/i

@ ./node_modules/@material-ui/core/esm/index.js

 @ ./src/App.jsx 2:0-46 5:42-51

@ ./src/bootstrap.jsx 1:0-24 4:50-53

@ ./src/index.js 1:0-21

 

ERROR in ./node_modules/@babel/runtime/helpers/es

Module not found: Error: Can't resolve './objectWabel\runtime\helpers\esm'

Did you mean 'objectWithoutPropertiesLoose.js'?

BREAKING CHANGE: The request './objectWithoutProp

(probably because the origin is a '*.mjs' file or

The extension in the request is mandatory for it

Add the extension to the request.

@ ./node_modules/@material-ui/core/esm/Zoom/Zoom

@ ./node_modules/@material-ui/core/esm/Zoom/inde

@ ./node_modules/@material-ui/core/esm/index.js

 @ ./src/App.jsx 2:0-46 5:42-51

@ ./src/bootstrap.jsx 1:0-24 4:50-53

@ ./src/index.js 1:0-21```

**Comment by jherr** [comment]
Ok, I've updated the project so that it's on the released Webpack 5.0.0. No
code changed, but a bunch of webpack.config.js changes since this example
was from Webpack 5 beta. Thanks for getting me to update this project.

**Comment by hamzaame** [comment]
@jherr Thank you very much. That was really helpful. But I see that `npm start` doesnt work.  It says compiled successfully but `localhost:3000` doesnt work. 
I have to run `npm run build` and then `npm run serve` only then app loads. Am I missing anything here?

**Comment by jherr** [comment]
Both `npm start` and `yarn start` work for me on port 8080. If you want to run the production build I recommend:

```
yarn build
cd dist
PORT=8080 npx serve
```

It's really important that the `publicPath` including the port number match where you are deploying to.
