### ISSUE TITLE
React Router with webpack 5

### ISSUE THREAD

**Issue by hamzaame** [jherr/wp5-starter-react#6]
Hi Jack, I didnt know where and how to send you a request. So creating this issue. Can you please add below things to this repo

1. some react router navigation .
2. Dockerizing this webpack5 app.

It will be of great help. Thank you in advance.

**Comment by jherr** [comment]
I want to keep it very lightweight. So feel free to fork a version and add react-router. But I will definitely do the Dockerizing. I think that's a capital idea.

**Comment by jherr** [comment]
Dockerfile added, as well as build and run commands in package.json.
