### ISSUE TITLE
breaking change - html-webpack-plugin

### ISSUE THREAD

**Issue by minmaxdata** [jherr/wp5-starter-react#7]
node --trace-deprecation ../../node_modules/webpack/bin/webpack.js
(node:12723) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
    at /Users/kmcadams/code/practical-module-federation/demo-mfed/node_modules/html-webpack-plugin/index.js:280:49
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
assets by chunk 2.39 MiB (id hint: vendors)
  asset vendors-node_modules_react-dom_index_js.js 2.21 MiB [emitted] (id hint: vendors)
  asset vendors-node_modules_react_index_js.js 180 KiB [emitted] (id hint: vendors)

there are newer versions of that plugin that fix this error

**Comment by jherr** [comment]
I talked with @scriptedalchemy about it and he says that it's basically just a warning. Apparently there is some issue in the HtmlPlugin. Looks ugly for sure though. Is your project not running?

**Comment by ScriptedAlchemy** [comment]
Upstage to the beta copy. Yarn install the next tag and it should get rid of the errors, it's not critical right now but those depreciations will eventually be removed

**Comment by ScriptedAlchemy** [comment]
https://github.com/dzintars/front/issues/45#issuecomment-714428695

**Comment by jherr** [comment]
Thanks! That works!
